spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fireshield
    username: app
    password: app
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.format_sql: true
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
  config:
    import: optional:file:.env

server:
  port: 8080

logging:
  level:
    root: info
    org.springframework.security: DEBUG
    org.hibernate.SQL: warn

app:
  jwt:
    secret: "CHANGE_ME_to_a_very_long_random_secret_value_at_least_64_bytes"
    expirySeconds: 7200
  cors:
    allowed-origins: "http://localhost:3000, http://127.0.0.1:3000, http://localhost:8080"
  ingest:
    device-header: "X-Device-Key"
  gemini:
    model: "gemini-2.5-flash"   # fast & low-cost; swap to gemini-2.0-pro for deeper reasoning
    maxOutputTokens: 512
    temperature: 0.3
