version: "3.9"

services:
  db:
    image: postgres:16
    container_name: fireshield-db
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: fireshield
    ports:
      - "5432:5432"   # host:container
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d fireshield"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  pgdata:
